In [11]:
True=10

SyntaxError: can't assign to keyword (<ipython-input-11-f9c1faaf4ad0>, line 1)

In [7]:
_

10

In [14]:
i=0
while i>=11:
    print(i)
    i+=1

In [20]:
i=0
while i<=10:
    i+=1
    print(i)
    

1
2
3
4
5
6
7
8
9
10
11


In [24]:
for i in range(0,11):
    if i==5:
        pass
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
# jumping statements
- break
- continue
- return
- pass

In [1]:
s1=set()

In [2]:
type(s1)

set

In [3]:
print(dir(set),end="")

['__and__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']

In [4]:
s1={1,23,4,'a','b','c'}

In [5]:
s1.add(3)

In [6]:
s1

{1, 23, 3, 4, 'a', 'b', 'c'}

In [7]:
s2={'djksn','ieqwuf'}
s1.update('saD','qwes')
s1

{1, 23, 3, 4, 'D', 'a', 'b', 'c', 'e', 'q', 's', 'w'}

In [8]:
s1

{1, 23, 3, 4, 'D', 'a', 'b', 'c', 'e', 'q', 's', 'w'}

In [9]:
s1.pop()

1

In [10]:
s1

{23, 3, 4, 'D', 'a', 'b', 'c', 'e', 'q', 's', 'w'}

In [11]:
s1.discard('a')
s1

{23, 3, 4, 'D', 'b', 'c', 'e', 'q', 's', 'w'}

In [12]:
s1.remove(23)
s1

{3, 4, 'D', 'b', 'c', 'e', 'q', 's', 'w'}

In [61]:
s1={1,2,3,'a','b','c'}
s2={4,5,3,'d','e','c'}

In [53]:
print(s1.union(s2))

{1, 2, 3, 'a', 'c', 4, 5, 'd', 'e', 'b'}


In [65]:
s1.intersection_update(s2)

In [67]:
s2

{3, 4, 5, 'c', 'd', 'e'}

In [55]:
s1.difference(s2)

{1, 2, 'a', 'b'}

In [56]:
s2.difference(s1)

{4, 5, 'd', 'e'}

In [57]:
s1.symmetric_difference(s2)

{1, 2, 4, 5, 'a', 'b', 'd', 'e'}

In [58]:
s1.issuperset(s2)

False

In [60]:
s1.issubset(s2)

False

In [ ]:
# Dictionaries
- collection of items
- pair of key and values called items
- represented with {}
- key must be unique.vales are acceted duplicates
- unordered
- mutable

In [73]:
d1={'key1':1, 'key2':[2,3,4,5,2], 3:'sthree'}
#type(d1)

In [74]:
d1

{'key1': 1, 'key2': [2, 3, 4, 5, 2], 3: 'sthree'}

In [77]:
d1['key2']

[2, 3, 4, 5, 2]

In [78]:
d1['key1']=11

In [79]:
d1['key1']

11

In [83]:
d1['key2']=12

In [84]:
d1

{'key1': 11, 'key2': 12, 3: 'sthree', 'newkey': 12}

In [85]:
print(dir(dict),end="")

['__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']

In [90]:
d1.get('key1')

11

In [91]:
d1.items()

dict_items([('key1', 11), ('key2', 12), (3, 'sthree'), ('newkey', 12)])

In [93]:
dict([(1,'one'),(2,'two')])

{1: 'one', 2: 'two'}

In [94]:
d1.keys()

dict_keys(['key1', 'key2', 3, 'newkey'])

In [95]:
d1.values()

dict_values([11, 12, 'sthree', 12])

In [97]:
d1.pop('key1')

11

In [101]:
d1.clear()

In [102]:
d1

{}

In [2]:
contacts={}
def addcontact(name,phone):
    if name not in contacts:
        contacts[name]=phone
        print("added successfully")
    else:
        print ("alredy exist")
addcontact('ravi',8099088)
addcontact('kishore',90999)
addcontact('surya',998898)
addcontact('surya',9089)

added successfully
added successfully
added successfully
alredy exist


In [104]:
contacts

{'ravi': 8099088, 'kishore': 90999, 'surya': 998898}

In [2]:
contacts={}
def addcontact(name,phone):
    if name not in contacts:
        contacts[name]=phone
        print("added successfully")
    else:
        print ("alredy exist")
#addcontact('ravi',8099088)
#addcontact('kishore',90999)
#addcontact('surya',998898)
#addcontact('surya',9089)
n=int(input())
for i in range(n):
    a=input().split()
    b=a[0]
    c=a[1]
    addcontact(b,c)

3
p 987
added successfully
q 890
added successfully
i 567
added successfully


In [110]:
a="malathi anits"
a.split()

['malathi', 'anits']

In [3]:
contacts

{'p': '987', 'q': '890', 'i': '567'}

In [3]:
def searchcontact(name):
    if name in contacts:
        print(contacts[name])
    else:
        print("contact not found")
n=input()
searchcontact(n)

surya
998898


In [4]:
def deletecontact(name):
    if name in contacts:
        contacts.pop(name)
        print("deleted successfully")
    else:
        print("not in contacts")
n=input()
deletecontact(n)

surya
deleted successfully


In [14]:
import re
s1="ravi kishore"
re.findall('i',s1)

['i', 'i']

In [ ]:
match()
search()
findall()

In [ ]:
^ - Beginning of the line
$ - Endinning of the line
. -allow any one character
\s- white spaces allowed
\S- non white spaces allowed
* -Repeats zero or more character
+ -Repeats one or more character
[0-9]-allow any one character of that particular list range
['a',0,1]- allow only these list of character
{}-range declaration

In [1]:
import re
s1="ravi kishore"
re.match('^[m,y]',s1)

In [2]:
s1=9898989898

In [3]:
def pv(n):
    pattern="^[6-9][0-9]{9}$|^[+][9][1][6-9][0-9]{9}$"
    if re.match(pattern,n):
        return True
    return False
n=input()
pv(n)

2342342423


False

In [ ]:
3ravi999@gmail.com
- user name "^[a-z0-9][0-9a-z._]{5,30}"
- @ [@]
- domain name [a-z0-9]{3,12}
- extension[.][a-z]{2,4}

In [6]:
def ev(email):
    pattern="^[a-z0-9][0-9a-z._]{5,30}[@][a-z0-9]{3,12}[.][a-z]{2,4}$"
    if re.match(pattern,email):
        return True
    return False
n=input()
ev(n)

3ravi999@gmail.com


True

In [19]:
contacts={}

In [23]:
def addcontacts(name,phone,email):
    if name in contacts:
        print("already exist")
    else:
        if not pv(phone):
            print("invalid phone number")
            return
        if not ev(email):
            print("invalid email")
            return
        newlist=[]
        newlist.append(phone)
        newlist.append(email)
        contacts[name]=newlist
        print("added successfully")
    return
#addcontacts("ravikishore2","9898989898","3ravi999@gmail.com")
n=int(input())
for i in range(n):
    a=input().split()
    b=a[0]
    c=a[1]
    d=a[2]
    addcontacts(b,c,d)

1
e


IndexError: list index out of range

In [18]:
contacts

{'ravikishore': ['9898989898', '3ravi999@gmail.com'],
 'ravikishore1': ['9898989898', '3ravi999@gmail.com'],
 'ravikishore2': ['9898989898', '3ravi999@gmail.com']}

# Files
- Files contains some data or info
- In python only two types of file either text
  file or binary file
## File handling 
C R U D
c- Create
R - Read
U- Update
D - Delete
### modes
x - Creating a file
w - If file not exist create a file.if file is      exist data is overwritten
r -if file exist read the data
a - If file not exist creates file.if file exist
update the info or data at end of the prious data

mode a and w 
write()
mode r
read()

In [32]:
f=open("f1.txt","r")
print(f.read())
f.close()

dataupdated info
updated info
updated info


In [33]:
name:kadlk
Branch:
year:
college:


SyntaxError: invalid syntax (<ipython-input-33-dcb6fc6a984b>, line 2)

In [34]:
f=open("f1.txt","w")
f.write("\nname:ravi \nbranch:ECE \nyear:3rd \ncollege:ANITS")
f.close()

In [35]:
f=open("f1.txt",'r')
print(f.read())
f.close()


name:ravi 
branch:ECE 
year:3rd 
college:ANITS


In [36]:
with open("f1.txt",'r') as d:
    print(d.read())



name:ravi 
branch:ECE 
year:3rd 
college:ANITS


In [37]:
with open ("f1.txt",'r') as f:
    c=0
    for i in f:
        c=c+1
    print(c)

5


In [45]:
with open ("f1.txt",'r') as f:
    print(f.readlines())

['name:ravi \n', 'branch:ECE \n', 'year:3rd \n', 'college:ANITS']


In [48]:
with open ("f1.txt",'r') as f:
    print(f.tell())
    print(f.seek(5))
    print(f.read())
    print(f.tell())

0
5
ravi 
branch:ECE 
year:3rd 
college:ANITS
46


In [50]:
with open ("f1.txt",'r+') as f:
    print(f.tell())
    print(f.read())
    print(f.tell())
    f.write("\nworkshop:Python")
    print(f.read())

0
name:ravi 
branch:ECE 
year:3rd 
college:ANITS
workshop:Python
63



In [88]:
with open ("input.txt",'w') as f:
    f.write("9\n11\n2\n5\n3\n7\n")
with open("input.txt",'r') as f:
    a=f.readlines()
    a.sort()
    print(a) 
with open("output.txt",'w') as f:
    for i in a:
        f.write(i)
    

['11\n', '2\n', '3\n', '5\n', '7\n', '9\n']


In [89]:
a=lambda x,y:x+y
a(3,4)

7

In [90]:
b=lambda x,y,z:x*y*z
b(4,5,6)

120

In [ ]:
map(functionname,iterablevariable)

In [98]:
def add(a):
    return a+a
list(map(add,range(1,10)))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [96]:
def mul(a):
    return a**2
c=range(1,11)
set(map(mul,c))

{1, 4, 9, 16, 25, 36, 49, 64, 81, 100}

In [101]:
li=[1,2,3,'a','b','c']
li=str(li)
li1=[]
for i in li:
    if i.isdigit():
        li1.append(i)
li1

['1', '2', '3']

In [104]:
n=input()
def f1(a):
    a=str(a)
    if a.isdigit():
        return True
list(filter(f1,n.split()))
    

1 2 3 a b c


['1', '2', '3']

In [4]:
def p(a):
    c=0
    if a>1:
        for i in range(2,a):
            if a%i==0:
                c=c+1
    if c==0:
        return True
    return False
list(filter(p,range(1,20)))

[1, 2, 3, 5, 7, 11, 13, 17, 19]

In [113]:
#comprehence
[i**2 for i in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [114]:
{i**2 for i in range(1,11)}

{1, 4, 9, 16, 25, 36, 49, 64, 81, 100}

In [115]:
{i:i**2 for i in range(1,11)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [117]:
tuple(i**2 for i in range(1,11))

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

In [118]:
[i*j for i in range(1,11) for j in range(11,12)]

[11, 22, 33, 44, 55, 66, 77, 88, 99, 110]

In [122]:
for i in range(1,11):
    for j in range(11,12):
        c=i*j
        print(c)

11
22
33
44
55
66
77
88
99
110


In [124]:
li=[1,2,3,'a','b','c']
[int(i) for i in str(li) if i.isdigit()]

[1, 2, 3]

In [ ]:
# Numpy
- numpy can divided into two parts first one is
  numarical(num) second one python(py)
- Array oriented computing
- Fast
- Convinent
- homogenous

In [186]:
import numpy as np
a=np.array([1,2,3.8,'c'])
a

array(['1', '2', '3.8', 'c'], dtype='<U32')

In [145]:
a[-1]

'c'

In [131]:
type(a)

numpy.ndarray

In [135]:
a.dtype

dtype('<U32')

In [133]:
a

array([1. , 2. , 3.8])

In [185]:
a.shape

(4,)

In [4]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b.shape

(3, 3)

In [6]:
c=b[1:,1]
c

array([5, 8])

In [183]:
c.shape

(2,)

In [7]:
paragraph=["There was a fox","It was seen near that farm sometime back"]
list1=[]
for sentence in paragraph:
    for word in sentence.split():
        list1.append(word)
print(list1)

['There', 'was', 'a', 'fox', 'It', 'was', 'seen', 'near', 'that', 'farm', 'sometime', 'back']


In [8]:
paragraph=["There was a fox","It was seen near that farm sometime back"]
list1=[]
for sentence in paragraph:
    list1.append(sentence)
print(list1)

['There was a fox', 'It was seen near that farm sometime back']


In [9]:
paragraph=["There was a fox","It was seen near that farm sometime back"]
list1=[]
for sentence in paragraph:
    for word in sentence.split():
        list1.append(word)
print(list1)

['There', 'was', 'a', 'fox', 'It', 'was', 'seen', 'near', 'that', 'farm', 'sometime', 'back']


In [40]:
s="suryanarayana"
print(s[0::2])
print(s[::-1])
print(s[-5:-1])
print(s[-20::])
print(s[:-1]+s[-1])

sraaaaa
anayaranayrus
ayan
suryanarayana
suryanarayana


In [45]:
n=int(input())
m=int(input())
print("Addition of %d and %d is %d"%(n,m,n+m))
print("Addition of %d and %d is %d"%(n,m,n*m))
print("Addition of {} and {} is {}".format(n,m,n+m))
print("Addition of {} and {} is {}".format(n,m,n+m))

2
3
Addition of 2 and 3 is 5
Addition of 2 and 3 is 6
Addition of 2 and 3 is 5
