In [1]:
import numpy as np

In [11]:
c=range(0,1000)
d=[i**5 for i in range(1,1000)]

In [12]:
%timeit list(map(lambda x,y:x*y,c,d))

140 µs ± 6.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [13]:
c1=np.array(c)
d1=np.array(d)

In [14]:
%timeit c1*d1

ValueError: operands could not be broadcast together with shapes (1000,) (999,) 

In [15]:
range(0,10)

range(0, 10)

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
- square matrices
- Transpose matrices
- identity matrices
- diagonal matrices
- zeros marices
- ones matrices
- inverse matrices

In [21]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [27]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
a=np.array([[1,2,3],[3,4,5]])

In [33]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [34]:
a.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [36]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
np.linalg.inv(b)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [38]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [52]:
np.random.random()

0.6712221079834779

In [100]:
50*np.random.random((3,3))+5

array([[ 8.17624172, 38.67513897, 49.79358375],
       [35.3900958 , 27.10391576, 24.06031072],
       [24.00960617, 33.48616793,  7.00091667]])

In [107]:
np.random.randint(2,30,(3,3))

array([[11, 22, 20],
       [10,  2, 23],
       [15, 12,  9]])

In [143]:
np.random.rand(3,3)

array([[0.08801822, 0.95993798, 0.55834522],
       [0.88716886, 0.53891109, 0.82299015],
       [0.04928708, 0.77245706, 0.28266381]])

In [145]:
np.linspace(1,50,100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [151]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [152]:
np.arange(12).reshape(2,-1,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [153]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[11,12,13]])

In [157]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [159]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

In [160]:
a+b

array([[ 8, 10, 12],
       [15, 17, 19]])

In [161]:
a-b

array([[-6, -6, -6],
       [-7, -7, -7]])

In [162]:
a*b

array([[ 7, 16, 27],
       [44, 60, 78]])

In [163]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.36363636, 0.41666667, 0.46153846]])

In [164]:
a%b

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [166]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [168]:
np.cos((a,b))

array([[[ 0.54030231, -0.41614684, -0.9899925 ],
        [-0.65364362,  0.28366219,  0.96017029]],

       [[ 0.75390225, -0.14550003, -0.91113026],
        [ 0.0044257 ,  0.84385396,  0.90744678]]])

In [173]:
a=1/np.tan(a)
a

array([[-1.1580523 ,  0.15406975, -6.91976674],
       [-0.86198006, -4.02400012, -3.23836034]])

In [176]:
np.std(a)

2.37160380145505

In [177]:
np.mean(a)

-2.674681636018873

In [181]:
np.max((a,b))

13.0

In [179]:
np.min(a)

-6.919766740589735

In [184]:
c=np.array([[1,2],[3,4]])

In [185]:
np.linalg.det(c)

-2.0000000000000004

In [190]:
d=np.array([[1,2],[3,4]])

In [191]:
np.dot(c,d)

array([[ 7, 10],
       [15, 22]])

In [193]:
np.sum((c,d))

20

In [194]:
np.exp(c)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
#pandas
Series
DataFrame

In [195]:
import pandas as pd

In [199]:
a=pd.Series([1,2,3,4,5.5,'d'])

In [200]:
a

0      1
1      2
2      3
3      4
4    5.5
5      d
dtype: object

In [201]:
a[0]

1

In [202]:
a[1:4]

1    2
2    3
3    4
dtype: object

In [206]:
pd.date_range(start='1-1-2019',end='1-1-2020')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10',
               ...
               '2019-12-23', '2019-12-24', '2019-12-25', '2019-12-26',
               '2019-12-27', '2019-12-28', '2019-12-29', '2019-12-30',
               '2019-12-31', '2020-01-01'],
              dtype='datetime64[ns]', length=366, freq='D')

In [232]:
pd.DataFrame([[1,2],[3,4]],index=['date','value'])

0  1
date   1  2
value  3  4

In [240]:
import numpy as np
marks=np.random.randint(1,100,size=20)
names=np.random.choice(['r1','r2','r3','r4','r5'],20)
avg=np.random.choice([50,60,30,67,89],20)

In [237]:
a=list(zip(marks,names,avg))

In [239]:
pd.DataFrame(a,columns=['marks','name','avg'])

marks name  avg
0      18   r4   89
1      58   r3   60
2      77   r4   89
3      69   r1   50
4      28   r4   67
5      46   r5   89
6      44   r2   89
7      32   r2   30
8      78   r5   60
9      56   r5   89
10     24   r5   67
11     72   r3   89
12     59   r4   60
13     32   r4   30
14     63   r3   89
15     67   r2   89
16     95   r3   50
17     80   r1   60
18     35   r3   67
19     48   r4   30

In [243]:
b=pd.DataFrame({'marks':marks,'name':names,'avg':avg})
b

marks name  avg
0      76   r1   89
1      31   r1   30
2      25   r5   67
3      71   r3   60
4      69   r3   67
5      10   r4   50
6      10   r3   67
7      83   r2   60
8       3   r3   50
9       5   r3   67
10      3   r1   67
11     33   r4   89
12     85   r4   60
13     40   r5   89
14     30   r5   50
15     83   r3   60
16     69   r3   60
17     60   r2   60
18     56   r1   50
19     30   r2   30

In [248]:
b.head(2)

marks name  avg
0     76   r1   89
1     31   r1   30

In [249]:
b.tail(2)

marks name  avg
18     56   r1   50
19     30   r2   30

In [263]:
b.columns

Index(['marks', 'name', 'avg'], dtype='object')

In [264]:
b.values

array([[76, 'r1', 89],
       [31, 'r1', 30],
       [25, 'r5', 67],
       [71, 'r3', 60],
       [69, 'r3', 67],
       [10, 'r4', 50],
       [10, 'r3', 67],
       [83, 'r2', 60],
       [3, 'r3', 50],
       [5, 'r3', 67],
       [3, 'r1', 67],
       [33, 'r4', 89],
       [85, 'r4', 60],
       [40, 'r5', 89],
       [30, 'r5', 50],
       [83, 'r3', 60],
       [69, 'r3', 60],
       [60, 'r2', 60],
       [56, 'r1', 50],
       [30, 'r2', 30]], dtype=object)

In [265]:
b.avg

0     89
1     30
2     67
3     60
4     67
5     50
6     67
7     60
8     50
9     67
10    67
11    89
12    60
13    89
14    50
15    60
16    60
17    60
18    50
19    30
Name: avg, dtype: int32

In [278]:
b.set_index('marks',inplace=True)

KeyError: 'marks'

In [269]:
b

name  avg
marks          
76      r1   89
31      r1   30
25      r5   67
71      r3   60
69      r3   67
10      r4   50
10      r3   67
83      r2   60
3       r3   50
5       r3   67
3       r1   67
33      r4   89
85      r4   60
40      r5   89
30      r5   50
83      r3   60
69      r3   60
60      r2   60
56      r1   50
30      r2   30

In [277]:
b.sort_values(by='avg',ascending=False)

name  avg
marks          
76      r1   89
40      r5   89
33      r4   89
10      r3   67
5       r3   67
3       r1   67
69      r3   67
25      r5   67
83      r2   60
71      r3   60
85      r4   60
83      r3   60
69      r3   60
60      r2   60
10      r4   50
3       r3   50
30      r5   50
56      r1   50
31      r1   30
30      r2   30

In [283]:
b.head()

name  avg
marks          
76      r1   89
31      r1   30
25      r5   67
71      r3   60
69      r3   67

In [292]:
#iloc
b.iloc[[1,4]]

name  avg
marks          
31      r1   30
69      r3   67

In [293]:
b.iloc[[True,False,True,True,False]]

name  avg
marks          
76      r1   89
25      r5   67
71      r3   60

In [300]:
b.head()

name  avg
marks          
76      r1   89
31      r1   30
25      r5   67
71      r3   60
69      r3   67

In [304]:
b.loc[[3]]

name  avg
marks          
3       r3   50
3       r1   67

In [313]:
b['avg'].describe()

count    20.000000
mean     61.100000
std      16.130716
min      30.000000
25%      50.000000
50%      60.000000
75%      67.000000
max      89.000000
Name: avg, dtype: float64

In [315]:
pd.read_csv('s1.csv')

name clg  marks  avg
0    r1   a     89   75
1    r2   b     87   72
2    r3   c     79   70

In [328]:
a=pd.DataFrame([[1,2],[3,4]],columns=['r1','r2'])
b=pd.DataFrame([[5,6],[7,8]],columns=['r11','r22'])

In [324]:
pd.concat([a,b],ignore_index=True)

r1  r2
0   1   2
1   3   4
2   5   6
3   7   8

In [329]:
a.join(b)

r1  r2  r11  r22
0   1   2    5    6
1   3   4    7    8