In [5]:
a=lambda x,y:x+y
a("surya","4")

'surya4'

In [2]:
b=lambda x,y,z:x*y*z
b(1,2,3)

6

map(functioname,iterablevariable)

In [6]:
def add(a):
    return a+a
list(map(add,range(1,10)))

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
def mul(a):
    return a**2
c=range(1,11)
set(map(mul,c))

{1, 4, 9, 16, 25, 36, 49, 64, 81, 100}

In [8]:
def mul(a):
    return a**2
c=range(1,11)
tuple(map(mul,c))

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

In [9]:
def add(a):
    return a+a
tuple(map(add,range(1,10)))

(2, 4, 6, 8, 10, 12, 14, 16, 18)

In [11]:
li=[1,2,3,'a','b','c']
li=str(li)
li1=[]
for i in li:
    if i.isdigit():
        li1.append(i)
li1

['1', '2', '3']

In [13]:
n=input()
def f1(a):
    a=str(a)
    if a.isdigit():
        return True
list(filter(f1,n.split()))

1 2 3 4 5 'a' 'surya'


['1', '2', '3', '4', '5']

In [17]:
def p(a):
    c=0
    if a>1:
        for i in range(1,a+1):
            if a%i==0:
                c=c+1
    if c==2:
        return True
    else:
        return False
list(filter(p,range(1,20)))

[2, 3, 5, 7, 11, 13, 17, 19]

In [18]:
def p(a):
    c=0
    if a>1:
        for i in range(2,a):
            if a%i==0:
                c=c+1
    if c==0:
        return True
    return False
list(filter(p,range(1,20)))

[1, 2, 3, 5, 7, 11, 13, 17, 19]

In [21]:
# comprenence
type([i**2 for i in range(1,11)])

list

In [22]:
{i**2 for i in range(1,11)}

{1, 4, 9, 16, 25, 36, 49, 64, 81, 100}

In [23]:
{i:i**2 for i in range(1,11)}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [24]:
tuple(i**2 for i in range(1,11))

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

In [29]:
[i*j for i in range(1,11) for j in range(1,11)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 40,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 60,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 70,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 80,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81,
 90,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100]

In [28]:
for i in range(1,11):
    for j in range(1,11):
        print(j)
    print(i)

1
2
3
4
5
6
7
8
9
10
1
1
2
3
4
5
6
7
8
9
10
2
1
2
3
4
5
6
7
8
9
10
3
1
2
3
4
5
6
7
8
9
10
4
1
2
3
4
5
6
7
8
9
10
5
1
2
3
4
5
6
7
8
9
10
6
1
2
3
4
5
6
7
8
9
10
7
1
2
3
4
5
6
7
8
9
10
8
1
2
3
4
5
6
7
8
9
10
9
1
2
3
4
5
6
7
8
9
10
10


In [30]:
li=[1,2,3,'a','b','c']
[int(i) for i in str(li) if i.isdigit()]

[1, 2, 3]

In [32]:
import numpy as np

In [33]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
c=b[1:,1]
c

array([5, 8])

In [75]:
c=b[1:,2]
c

array([6, 9])

In [78]:
c=np.arange(100)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
type(c)

numpy.ndarray

In [81]:
a

<function __main__.<lambda>(x, y)>

In [83]:
a.shaped

AttributeError: 'function' object has no attribute 'shape'

In [84]:
s="s"
type(s)

str