In [1]:
a=[[1,4,5],[-5,7,8]]
a

[[1, 4, 5], [-5, 7, 8]]

In [11]:
a = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
a
print(a[1])
print(a[1][2])
print(a[0])s
print(a[0][-1])
print(a[0][-2])
print(a[-1])
print(a[1::][2::])

[-5, 8, 9, 0]
9
[1, 4, 5, 12]
12
5
[-6, 7, 11, 19]
[]


In [12]:
column = []
for row in a:
    column.append(row[2])
print("3rd column =",column)

3rd column = [5, 9, 11]


In [16]:
column = []
for row in a:
    column.append(row[0])
print("3rd column =",column)

3rd column = [1, -5, -6]


In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
type(np.array([1,2,3]))


numpy.ndarray

In [10]:
b=np.array([1,2,3])
b.dtype

dtype('int32')

In [6]:
a=np.array([1,2,3,4.5])
a

array([1. , 2. , 3. , 4.5])

In [7]:
a.dtype

dtype('float64')

In [12]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c.shape

(2, 3)

In [14]:
c.ndim

2

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
d=range(100)

In [17]:
d

range(0, 100)

In [18]:
d.arange(100)

AttributeError: 'range' object has no attribute 'arange'

In [19]:
%timeit [i**5 for i in c]

7.17 µs ± 85.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [1]:
import pandas as pd

In [2]:
a=pd.Series([1,2,3,4,5])

In [3]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(a)

pandas.core.series.Series

In [5]:
a[2]

3

In [6]:
a[::-1]

4    5
3    4
2    3
1    2
0    1
dtype: int64

In [7]:
a[-3:-1]

2    3
3    4
dtype: int64

In [8]:
a[-1:]

4    5
dtype: int64

In [9]:
a=pd.Series(['a','b','c',11])

In [10]:
a

0     a
1     b
2     c
3    11
dtype: object

In [11]:
a=pd.date_range(start='01-01-2020', end='01-12-2020')

In [12]:
a

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
              dtype='datetime64[ns]', freq='D')

In [13]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

In [15]:
import numpy as np
temp=np.random.randint(low=0,high=100,size=[20])
print(temp)

[57 36 88 80 23 58 12 75 56 58 97 58 92 52 37 76 98 19 33 83]


In [16]:
name = np.random.choice(['surya','venkat','narayana','narla'],20)
print(name)

['narla' 'surya' 'narayana' 'surya' 'narayana' 'narayana' 'venkat'
 'venkat' 'narayana' 'narayana' 'venkat' 'venkat' 'narla' 'surya' 'narla'
 'narayana' 'narayana' 'narla' 'narayana' 'narayana']


In [17]:
av=np.random.choice([10,12,13,34,56],20)
print(av)

[56 12 12 10 12 34 12 10 10 56 56 56 34 13 12 12 56 56 34 10]


In [18]:
a=list(zip(temp,name,av))
a

[(57, 'narla', 56),
 (36, 'surya', 12),
 (88, 'narayana', 12),
 (80, 'surya', 10),
 (23, 'narayana', 12),
 (58, 'narayana', 34),
 (12, 'venkat', 12),
 (75, 'venkat', 10),
 (56, 'narayana', 10),
 (58, 'narayana', 56),
 (97, 'venkat', 56),
 (58, 'venkat', 56),
 (92, 'narla', 34),
 (52, 'surya', 13),
 (37, 'narla', 12),
 (76, 'narayana', 12),
 (98, 'narayana', 56),
 (19, 'narla', 56),
 (33, 'narayana', 34),
 (83, 'narayana', 10)]

In [19]:
df=pd.DataFrame(data=a,columns=['rollno','name','data'])
print(df)

    rollno      name  data
0       57     narla    56
1       36     surya    12
2       88  narayana    12
3       80     surya    10
4       23  narayana    12
5       58  narayana    34
6       12    venkat    12
7       75    venkat    10
8       56  narayana    10
9       58  narayana    56
10      97    venkat    56
11      58    venkat    56
12      92     narla    34
13      52     surya    13
14      37     narla    12
15      76  narayana    12
16      98  narayana    56
17      19     narla    56
18      33  narayana    34
19      83  narayana    10


In [31]:
type(df)

pandas.core.frame.DataFrame

In [32]:
df=pd.DataFrame({'temp':temp,'name':name,'av':av})
print(df)

    temp      name  av
0     57     narla  56
1     36     surya  12
2     88  narayana  12
3     80     surya  10
4     23  narayana  12
5     58  narayana  34
6     12    venkat  12
7     75    venkat  10
8     56  narayana  10
9     58  narayana  56
10    97    venkat  56
11    58    venkat  56
12    92     narla  34
13    52     surya  13
14    37     narla  12
15    76  narayana  12
16    98  narayana  56
17    19     narla  56
18    33  narayana  34
19    83  narayana  10


In [33]:
df.head()

temp      name  av
0    57     narla  56
1    36     surya  12
2    88  narayana  12
3    80     surya  10
4    23  narayana  12

In [34]:
df.tail()

temp      name  av
15    76  narayana  12
16    98  narayana  56
17    19     narla  56
18    33  narayana  34
19    83  narayana  10

In [35]:
df.shape


(20, 3)

In [36]:
df.columns

Index(['temp', 'name', 'av'], dtype='object')

In [37]:
df.name

0        narla
1        surya
2     narayana
3        surya
4     narayana
5     narayana
6       venkat
7       venkat
8     narayana
9     narayana
10      venkat
11      venkat
12       narla
13       surya
14       narla
15    narayana
16    narayana
17       narla
18    narayana
19    narayana
Name: name, dtype: object

In [38]:
df['name']

0        narla
1        surya
2     narayana
3        surya
4     narayana
5     narayana
6       venkat
7       venkat
8     narayana
9     narayana
10      venkat
11      venkat
12       narla
13       surya
14       narla
15    narayana
16    narayana
17       narla
18    narayana
19    narayana
Name: name, dtype: object

In [39]:
df['temp']

0     57
1     36
2     88
3     80
4     23
5     58
6     12
7     75
8     56
9     58
10    97
11    58
12    92
13    52
14    37
15    76
16    98
17    19
18    33
19    83
Name: temp, dtype: int32

In [40]:
df['temp'].describe()

count    20.000000
mean     59.400000
std      26.470241
min      12.000000
25%      36.750000
50%      58.000000
75%      80.750000
max      98.000000
Name: temp, dtype: float64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
rollno    20 non-null int64
name      20 non-null object
data      20 non-null int64
dtypes: int64(2), object(1)
memory usage: 560.0+ bytes


In [41]:
df.values

array([[57, 'narla', 56],
       [36, 'surya', 12],
       [88, 'narayana', 12],
       [80, 'surya', 10],
       [23, 'narayana', 12],
       [58, 'narayana', 34],
       [12, 'venkat', 12],
       [75, 'venkat', 10],
       [56, 'narayana', 10],
       [58, 'narayana', 56],
       [97, 'venkat', 56],
       [58, 'venkat', 56],
       [92, 'narla', 34],
       [52, 'surya', 13],
       [37, 'narla', 12],
       [76, 'narayana', 12],
       [98, 'narayana', 56],
       [19, 'narla', 56],
       [33, 'narayana', 34],
       [83, 'narayana', 10]], dtype=object)

In [42]:
df.set_index('temp')

name  av
temp              
57       narla  56
36       surya  12
88    narayana  12
80       surya  10
23    narayana  12
58    narayana  34
12      venkat  12
75      venkat  10
56    narayana  10
58    narayana  56
97      venkat  56
58      venkat  56
92       narla  34
52       surya  13
37       narla  12
76    narayana  12
98    narayana  56
19       narla  56
33    narayana  34
83    narayana  10

In [43]:
df.set_index('temp',inplace=True)
print(df)

          name  av
temp              
57       narla  56
36       surya  12
88    narayana  12
80       surya  10
23    narayana  12
58    narayana  34
12      venkat  12
75      venkat  10
56    narayana  10
58    narayana  56
97      venkat  56
58      venkat  56
92       narla  34
52       surya  13
37       narla  12
76    narayana  12
98    narayana  56
19       narla  56
33    narayana  34
83    narayana  10


In [45]:
df.sort_index(axis=2,ascending=False)

ValueError: No axis named 2 for object type <class 'type'>

In [46]:
df.sort_values(by='av',ascending=True)

name  av
temp              
83    narayana  10
80       surya  10
75      venkat  10
56    narayana  10
36       surya  12
88    narayana  12
23    narayana  12
12      venkat  12
37       narla  12
76    narayana  12
52       surya  13
58    narayana  34
33    narayana  34
92       narla  34
19       narla  56
98    narayana  56
57       narla  56
97      venkat  56
58      venkat  56
58    narayana  56

In [47]:
df.drop(['av'],axis=1)

name
temp          
57       narla
36       surya
88    narayana
80       surya
23    narayana
58    narayana
12      venkat
75      venkat
56    narayana
58    narayana
97      venkat
58      venkat
92       narla
52       surya
37       narla
76    narayana
98    narayana
19       narla
33    narayana
83    narayana

In [48]:
df.iloc[[0,1]]

name  av
temp           
57    narla  56
36    surya  12

In [49]:
df.iloc[1:3,1]

temp
36    12
88    12
Name: av, dtype: int32

In [50]:
df.iloc[[True,True,False,True]]

name  av
temp           
57    narla  56
36    surya  12
80    surya  10

In [51]:
df.iloc[0,:]

name    narla
av         56
Name: 57, dtype: object

In [52]:
df.head()

name  av
temp              
57       narla  56
36       surya  12
88    narayana  12
80       surya  10
23    narayana  12

In [53]:
df.loc[57]

name    narla
av         56
Name: 57, dtype: object

In [54]:
df.loc[[57,36,88]]


name  av
temp              
57       narla  56
36       surya  12
88    narayana  12

In [55]:
df.loc[df.av>12]

name  av
temp              
57       narla  56
58    narayana  34
58    narayana  56
97      venkat  56
58      venkat  56
92       narla  34
52       surya  13
98    narayana  56
19       narla  56
33    narayana  34

In [57]:
df.loc[(df.av>56) | (df.av==10)]
print(df)

          name  av
temp              
57       narla  56
36       surya  12
88    narayana  12
80       surya  10
23    narayana  12
58    narayana  34
12      venkat  12
75      venkat  10
56    narayana  10
58    narayana  56
97      venkat  56
58      venkat  56
92       narla  34
52       surya  13
37       narla  12
76    narayana  12
98    narayana  56
19       narla  56
33    narayana  34
83    narayana  10


In [58]:
df.loc[(df.av==10)]

name  av
temp              
80       surya  10
75      venkat  10
56    narayana  10
83    narayana  10

# merging

In [59]:
d1 = pd.DataFrame([['a',1],['b',2]],columns=['col1','number'])

In [60]:
d1

col1  number
0    a       1
1    b       2

In [63]:
d2=pd.DataFrame([['c',3,'lion'],['d',4,'tiger']],columns=['letter','number','animal'])

In [64]:
print(d2)

  letter  number animal
0      c       3   lion
1      d       4  tiger


In [65]:
pd.concat([d1,d2],axis=0)


C:\Users\Satya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
0   lion  NaN      c       3
1  tiger  NaN      d       4